apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: dbaas-api
  namespace: observability
  
  labels:
    release: kube-prometheus-stack

spec:
  namespaceSelector:
    matchNames:
      - dbaas-api

  selector:
    matchLabels:
      app.kubernetes.io/name: dbaas-api

  endpoints:
    - port: http
      path: /metrics
      interval: 15s