apiVersion: v1
kind: ConfigMap
metadata:
  name: dbaas-api-config
  namespace: dbaas-api
data:
  APP_ENV: "production"
  APP_LOG_LEVEL: "info"
  SERVER_ADDRESS: ":8080"
  SERVER_ALLOW_ORIGINS: "https://app.foyez.runs.onstackit.cloud"
  ZITADEL_DOMAIN: "dbaas-jhuvx5.eu1.zitadel.cloud"
  ZITADEL_KEY_PATH: "/var/run/secrets/zitadel/zitadel-key.json"