apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbaas-deploy
  namespace: dbaas-api
spec:
  selector:
    matchLabels:
      app: dbaas
  replicas: 2
  template:
    metadata:
      labels:
        app: dbaas
    spec:
      serviceAccountName: dbaas-api
      imagePullSecrets:
        - name: stackit-registry-secret

      containers:
        - name: dbaas-api
          image: registry.onstackit.cloud/dbaas-platform/dbaas-platform-api:latest
          ports:
            - containerPort: 8080

          
          env:
            - name: ZITADEL_DOMAIN
              value: "dbaas-jhuvx5.eu1.zitadel.cloud"

            - name: ZITADEL_KEY_PATH
              value: "/var/run/secrets/zitadel/zitadel-key.json"

          volumeMounts:
            - name: zitadel-key
              mountPath: /var/run/secrets/zitadel
              readOnly: true
              
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: dbaas-svc
  namespace: dbaas-api
spec:
  type: ClusterIP
  selector:
    app: dbaas
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
