apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: loki
    repo: https://grafana-community.github.io/helm-charts
    version: 18.9.0
    releaseName: dbaas-loki
    namespace: observability
    valuesFile: values.yaml