# @baseUrl = http://localhost:8080
@baseUrl = http://foyez.runs.onstackit.cloud
@apiV1 = {{baseUrl}}/api/v1
@contentType = application/json
@instanceID = 9990e61c-c783-4ccb-8f91-a7365a298dfb

### Create Instance
POST {{apiV1}}/instances
Idempotency-Key: 8ad1fdf6-4b6e-48b0-bec2-3c6c4f386632
Content-Type: {{contentType}}

{
  "name": "my-db-2",
  "version": 16,
  "storage": "10Gi"
}

### List Instances
GET {{apiV1}}/instances

### Delete Instance
DELETE {{apiV1}}/instances/{{instanceID}}