apiVersion: database.example.com/v1
kind: PostgreSQL

metadata:
  name: internal-db
  namespace: database-system

spec:
  version: "16"
  instances: 1
  storage: 2Gi
  database: customerdb
  username: customer-admin
