replicas: 1

persistence:
  enabled: true
  type: pvc
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP

grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/"

  analytics:
    reporting_enabled: false
    check_for_updates: false

  users:
    allow_sign_up: false

  security:
    disable_gravatar: true