apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dbaas-operator

resources:
  - ../../base

images:
  - name: controller
    newName: docker.io/foyezar/postgres-platform-operator
    newTag: eadb9cf