apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: database-resources
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://level3.git.onstackit.cloud/LEVEL3/foyez-inra.git
    targetRevision: main
    path: gitops/database/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: database-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true