apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/cnpg.yaml
  - apps/dbaas-operator.yaml
  - apps/dbaas-api.yaml
  - apps/dbaas-client.yaml
  # - apps/database-resource.yaml